// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC88uC-IJnpt5n0F7bHOg9ESVXBhMmKzgc',
    appId: '1:688076092208:web:525f74c6d595d4055e4ef5',
    messagingSenderId: '688076092208',
    projectId: 'citymove-4e8b1',
    authDomain: 'citymove-4e8b1.firebaseapp.com',
    storageBucket: 'citymove-4e8b1.firebasestorage.app',
    measurementId: 'G-CE1BQ331HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDla1XIdB_Ee9UsfxPH9HaRZxMg_Mih4Wk',
    appId: '1:688076092208:android:aebad98a0d6cce5d5e4ef5',
    messagingSenderId: '688076092208',
    projectId: 'citymove-4e8b1',
    storageBucket: 'citymove-4e8b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1kdKnPqwt91ETwQ2EPFnxAMSoM2u6J0',
    appId: '1:688076092208:ios:a92ad87b48cb8a8e5e4ef5',
    messagingSenderId: '688076092208',
    projectId: 'citymove-4e8b1',
    storageBucket: 'citymove-4e8b1.firebasestorage.app',
    iosBundleId: 'com.example.citymove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1kdKnPqwt91ETwQ2EPFnxAMSoM2u6J0',
    appId: '1:688076092208:ios:a92ad87b48cb8a8e5e4ef5',
    messagingSenderId: '688076092208',
    projectId: 'citymove-4e8b1',
    storageBucket: 'citymove-4e8b1.firebasestorage.app',
    iosBundleId: 'com.example.citymove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC88uC-IJnpt5n0F7bHOg9ESVXBhMmKzgc',
    appId: '1:688076092208:web:6f36e2e0a2f4c7545e4ef5',
    messagingSenderId: '688076092208',
    projectId: 'citymove-4e8b1',
    authDomain: 'citymove-4e8b1.firebaseapp.com',
    storageBucket: 'citymove-4e8b1.firebasestorage.app',
    measurementId: 'G-MZ0VVKYDHR',
  );
}
