// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJY4C-ccYi2qz7irDZwqLNks87_Cf4R5c',
    appId: '1:758434239933:web:9b39dcf8b32a68583beed4',
    messagingSenderId: '758434239933',
    projectId: 'citymove-4a423',
    authDomain: 'citymove-4a423.firebaseapp.com',
    storageBucket: 'citymove-4a423.firebasestorage.app',
    measurementId: 'G-VVXPE7QJ4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmR_gGfQrQ2hH8-i3eIkzxWwNuPckWu9s',
    appId: '1:758434239933:android:620f506f475a1e443beed4',
    messagingSenderId: '758434239933',
    projectId: 'citymove-4a423',
    storageBucket: 'citymove-4a423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWfobcIbzehAnrQ4ClqClMyABuV0GQHg',
    appId: '1:758434239933:ios:9612ed197a0a3dc13beed4',
    messagingSenderId: '758434239933',
    projectId: 'citymove-4a423',
    storageBucket: 'citymove-4a423.firebasestorage.app',
    iosBundleId: 'com.example.citymove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWfobcIbzehAnrQ4ClqClMyABuV0GQHg',
    appId: '1:758434239933:ios:9612ed197a0a3dc13beed4',
    messagingSenderId: '758434239933',
    projectId: 'citymove-4a423',
    storageBucket: 'citymove-4a423.firebasestorage.app',
    iosBundleId: 'com.example.citymove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJY4C-ccYi2qz7irDZwqLNks87_Cf4R5c',
    appId: '1:758434239933:web:1bac3f6cbc2b9cb13beed4',
    messagingSenderId: '758434239933',
    projectId: 'citymove-4a423',
    authDomain: 'citymove-4a423.firebaseapp.com',
    storageBucket: 'citymove-4a423.firebasestorage.app',
    measurementId: 'G-W5W351S5KJ',
  );
}
